[def.rcc.base]
default_value = 0x40021000
allowed_values = [
    [ 0x40021000 ],
    [ 0x40021000 ]
]

[def.clock.source]
default_value = 'hsi'
allowed_values = [
    [ 'hsi', 'hse', 'pll' ],
    [     0,     1,     2 ]
]

[def.clock.usb_prescale]
default_value = 1.5
allowed_values = [
    [ 1.5, 1.0 ],
    [   0,   1 ]
]

[def.clock.adc_prescale]
default_value = 2
allowed_values = [
    [ 2, 4, 6, 8 ],
    [ 0, 1, 2, 3 ]
]

[def.clock.pll_source]
default_value = 'hsi_div2'
allowed_values = [
    [ 'hsi_div2', 'hse' ],
    [          0,     1 ],
]

[def.clock.pll_entry_divider]
default_value = 1
allowed_values = [
    [ 1, 2 ],
    [ 0, 1 ]
]

[def.clock.apb1_prescale]
default_value = 1
allowed_values = [
    [ 1, 2, 4, 8, 16 ],
    [ 0, 4, 5, 6,  7 ]
]

[def.clock.apb2_prescale]
default_value = 1
allowed_values = [
    [ 1, 2, 4, 8, 16 ],
    [ 0, 4, 5, 6,  7 ]
]

[def.clock.ahb_prescale]
default_value = 1
allowed_values = [
    [ 1, 2, 4,  8, 16, 64, 128, 256, 512 ],
    [ 0, 8, 9, 10, 11, 12,  13,  14,  15 ]
]

[def.clock.output]
default_value = 'none'
allowed_values = [
    [ 'none', 'sysclock', 'hs1', 'hse', 'pll_div2' ],
    [      0,          4,     5,     6,          7 ]
]

[def.clock.pll_multiplier]
default_value = 2
allowed_values = [
    [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ],
    [ 0, 1, 2, 3, 4, 5, 6, 7,  8,  9, 10, 11, 12, 13, 14 ]
]
